name: ict_hack
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-56.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  intl: ^0.17.0
  flutter_svg: ^1.0.0
  flutter_slidable: ^1.1.0
  grouped_list: ^4.1.0
  http: ^0.13.4
  bot_toast: ^4.0.1
  easy_localization: ^3.0.0
  clipboard: ^0.1.3
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/avatar/blush/
    - assets/avatar/bodies/
    - assets/avatar/brows/
    - assets/avatar/eyes/
    - assets/avatar/glasses/
    - assets/avatar/hairstyles/
    - assets/avatar/mouth/

    - assets/clothes/boots/
    - assets/clothes/pants/
    - assets/clothes/t_shirts/

    - assets/achievments/